In [1]:
import gdown
import pandas as pd
# Replace with your actual file ID from Drive link
file_id = "1AbCdEfGHIjklmnopQRstuVWxyz"
url = f"https://drive.google.com/uc?id={file_id}"
output = "raw_data.csv"



df = pd.read_csv("raw_data.csv")

In [2]:
print(df.shape)        # rows, cols
print(df.info())       # data types, nulls
print(df.head())       # first rows
print(df.isnull().sum())  # count of missing values

(20001, 27)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20001 entries, 0 to 20000
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Income                           19998 non-null  float64
 1   Age                              20000 non-null  float64
 2   Dependents                       20000 non-null  float64
 3   Occupation                       19998 non-null  object
 4   City_Tier                        19999 non-null  object
 5   Rent                             20000 non-null  object
 6   Loan_Repayment                   20000 non-null  float64
 7   Insurance                        19999 non-null  float64
 8   Groceries                        20000 non-null  float64
 9   Transport                        19999 non-null  float64
 10  Eating_Out                       19999 non-null  float64
 11  Entertainment                    20000 non-null  float64
 12  Utilities                        19998 non-null  float64
 13  Healthcare                       19999 non-null  float64
 14  Education                        20000 non-null  float64
 15  Miscellaneous                    20000 non-null  float64
 16  Desired_Savings_Percentage       20000 non-null  float64
 17  Desired_Savings                  20000 non-null  float64
 18  Disposable_Income                20000 non-null  float64
 19  Potential_Savings_Groceries      20000 non-null  float64
 20  Potential_Savings_Transport      20000 non-null  float64
 21  Potential_Savings_Eating_Out     20000 non-null  float64
 22  Potential_Savings_Entertainment  20000 non-null  float64
 23  Potential_Savings_Utilities      20000 non-null  float64
 24  Potential_Savings_Healthcare     20000 non-null  float64
 25  Potential_Savings_Education      19999 non-null  float64
 26  Potential_Savings_Miscellaneous  20000 non-null  float64
dtypes: float64(24), object(3)
memory usage: 4.1+ MB
None
         Income   Age  Dependents     Occupation City_Tier         Rent  \
0   44637.24964  49.0         0.0  Self_Employed    Tier_1  13391.17489
1   26858.59659  34.0         2.0        Retired    Tier_2  5371.719318
2   50367.60508  35.0         1.0        student    Tier_3  7555.140763
3  101455.60020  21.0         0.0  Self_Employed    Tier_3  15218.34004
4   24875.28355  52.0         4.0   Professional    Tier_2   4975.05671

   Loan_Repayment    Insurance     Groceries    Transport  ...  \
0        0.000000  2206.490129   6658.768341  2636.970696  ...
1        0.000000   869.522617   2818.444460  1543.018778  ...
2     4612.103386  2201.800050   6313.222081  3221.396403  ...
3     6809.441427  4889.418087  14690.149360  7106.130005  ...
4     3112.609398   635.907170   3034.329665  1276.155163  ...

   Desired_Savings  Disposable_Income  Potential_Savings_Groceries  \
0      6200.537192       11265.627710                  1685.696222
1      1923.176434        9676.818733                   540.306561
2      7050.360422       13891.450620                  1466.073984
3     16694.965140       31617.953610                  1875.932770
4      1874.099434        6265.700532                   788.953124

   Potential_Savings_Transport  Potential_Savings_Eating_Out  \
0                   328.895281                    465.769172
1                   119.347139                    141.866089
2                   473.549752                    410.857129
3                   762.020789                   1241.017448
4                    68.160766                     61.712505

   Potential_Savings_Entertainment  Potential_Savings_Utilities  \
0                       195.151320                   678.292859
1                       234.131168                   286.668408
2                       459.965257                   488.383423
3                       320.190594                  1389.815033
4                       187.173750                   194.117130

   Potential_Savings_Healthcare  Potential_Savings_Education  \
0                     67.682471                     0.000000
1                      6.603212                    56.306874
2                      7.290892                   106.653597
3                    193.502754                     0.000000
4                     47.294591                    67.388120

   Potential_Savings_Miscellaneous
0                        85.735517
1                        97.388606
2                       138.542422
3                       296.041183
4                        96.557076

[5 rows x 27 columns]
Income                             3
Age                                1
Dependents                         1
Occupation                         3
City_Tier                          2
Rent                               1
Loan_Repayment                     1
Insurance                          2
Groceries                          1
Transport                          2
Eating_Out                         2
Entertainment                      1
Utilities                          3
Healthcare                         2
Education                          1
Miscellaneous                      1
Desired_Savings_Percentage         1
Desired_Savings                    1
Disposable_Income                  1
Potential_Savings_Groceries        1
Potential_Savings_Transport        1
Potential_Savings_Eating_Out       1
Potential_Savings_Entertainment    1
Potential_Savings_Utilities        1
Potential_Savings_Healthcare       1
Potential_Savings_Education        2
Potential_Savings_Miscellaneous    1
dtype: int64

In [3]:
df = df.dropna(how='all')

In [4]:
df.shape

(20000, 27)

In [5]:
df = df.loc[:, ~df.columns.str.contains("^Unnamed")]

In [6]:
print("Number of columns:", df.shape[1])
print("Column names:", df.columns.tolist())

Number of columns: 27
Column names: ['Income', 'Age', 'Dependents', 'Occupation', 'City_Tier', 'Rent', 'Loan_Repayment', 'Insurance', 'Groceries', 'Transport', 'Eating_Out', 'Entertainment', 'Utilities', 'Healthcare', 'Education', 'Miscellaneous', 'Desired_Savings_Percentage', 'Desired_Savings', 'Disposable_Income', 'Potential_Savings_Groceries', 'Potential_Savings_Transport', 'Potential_Savings_Eating_Out', 'Potential_Savings_Entertainment', 'Potential_Savings_Utilities', 'Potential_Savings_Healthcare', 'Potential_Savings_Education', 'Potential_Savings_Miscellaneous']

In [7]:
df['Age'] = df['Age'].astype(int)
df['Dependents'] = df['Dependents'].astype(int)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20000 entries, 0 to 20000
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Income                           19998 non-null  float64
 1   Age                              20000 non-null  int64
 2   Dependents                       20000 non-null  int64
 3   Occupation                       19998 non-null  object
 4   City_Tier                        19999 non-null  object
 5   Rent                             20000 non-null  object
 6   Loan_Repayment                   20000 non-null  float64
 7   Insurance                        19999 non-null  float64
 8   Groceries                        20000 non-null  float64
 9   Transport                        19999 non-null  float64
 10  Eating_Out                       19999 non-null  float64
 11  Entertainment                    20000 non-null  float64
 12  Utilities                        19998 non-null  float64
 13  Healthcare                       19999 non-null  float64
 14  Education                        20000 non-null  float64
 15  Miscellaneous                    20000 non-null  float64
 16  Desired_Savings_Percentage       20000 non-null  float64
 17  Desired_Savings                  20000 non-null  float64
 18  Disposable_Income                20000 non-null  float64
 19  Potential_Savings_Groceries      20000 non-null  float64
 20  Potential_Savings_Transport      20000 non-null  float64
 21  Potential_Savings_Eating_Out     20000 non-null  float64
 22  Potential_Savings_Entertainment  20000 non-null  float64
 23  Potential_Savings_Utilities      20000 non-null  float64
 24  Potential_Savings_Healthcare     20000 non-null  float64
 25  Potential_Savings_Education      19999 non-null  float64
 26  Potential_Savings_Miscellaneous  20000 non-null  float64
dtypes: float64(22), int64(2), object(3)
memory usage: 4.3+ MB

In [9]:
df['Income'] = df['Income'].fillna(df['Income'].mean())
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mean())

In [10]:
df.dtypes

Income                             float64
Age                                  int64
Dependents                           int64
Occupation                          object
City_Tier                           object
Rent                                object
Loan_Repayment                     float64
Insurance                          float64
Groceries                          float64
Transport                          float64
Eating_Out                         float64
Entertainment                      float64
Utilities                          float64
Healthcare                         float64
Education                          float64
Miscellaneous                      float64
Desired_Savings_Percentage         float64
Desired_Savings                    float64
Disposable_Income                  float64
Potential_Savings_Groceries        float64
Potential_Savings_Transport        float64
Potential_Savings_Eating_Out       float64
Potential_Savings_Entertainment    float64
Potential_Savings_Utilities        float64
Potential_Savings_Healthcare       float64
Potential_Savings_Education        float64
Potential_Savings_Miscellaneous    float64
dtype: object

In [11]:
df.isnull().sum()

Income                             0
Age                                0
Dependents                         0
Occupation                         2
City_Tier                          1
Rent                               0
Loan_Repayment                     0
Insurance                          1
Groceries                          0
Transport                          1
Eating_Out                         1
Entertainment                      0
Utilities                          2
Healthcare                         1
Education                          0
Miscellaneous                      0
Desired_Savings_Percentage         0
Desired_Savings                    0
Disposable_Income                  0
Potential_Savings_Groceries        0
Potential_Savings_Transport        0
Potential_Savings_Eating_Out       0
Potential_Savings_Entertainment    0
Potential_Savings_Utilities        0
Potential_Savings_Healthcare       0
Potential_Savings_Education        1
Potential_Savings_Miscellaneous    0
dtype: int64

In [12]:
df.shape

(20000, 27)

In [13]:
df = df.dropna(how='any')

In [14]:
df.isnull().sum()

Income                             0
Age                                0
Dependents                         0
Occupation                         0
City_Tier                          0
Rent                               0
Loan_Repayment                     0
Insurance                          0
Groceries                          0
Transport                          0
Eating_Out                         0
Entertainment                      0
Utilities                          0
Healthcare                         0
Education                          0
Miscellaneous                      0
Desired_Savings_Percentage         0
Desired_Savings                    0
Disposable_Income                  0
Potential_Savings_Groceries        0
Potential_Savings_Transport        0
Potential_Savings_Eating_Out       0
Potential_Savings_Entertainment    0
Potential_Savings_Utilities        0
Potential_Savings_Healthcare       0
Potential_Savings_Education        0
Potential_Savings_Miscellaneous    0
dtype: int64

In [15]:
df.shape

(19991, 27)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19991 entries, 0 to 20000
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Income                           19991 non-null  float64
 1   Age                              19991 non-null  int64
 2   Dependents                       19991 non-null  int64
 3   Occupation                       19991 non-null  object
 4   City_Tier                        19991 non-null  object
 5   Rent                             19991 non-null  object
 6   Loan_Repayment                   19991 non-null  float64
 7   Insurance                        19991 non-null  float64
 8   Groceries                        19991 non-null  float64
 9   Transport                        19991 non-null  float64
 10  Eating_Out                       19991 non-null  float64
 11  Entertainment                    19991 non-null  float64
 12  Utilities                        19991 non-null  float64
 13  Healthcare                       19991 non-null  float64
 14  Education                        19991 non-null  float64
 15  Miscellaneous                    19991 non-null  float64
 16  Desired_Savings_Percentage       19991 non-null  float64
 17  Desired_Savings                  19991 non-null  float64
 18  Disposable_Income                19991 non-null  float64
 19  Potential_Savings_Groceries      19991 non-null  float64
 20  Potential_Savings_Transport      19991 non-null  float64
 21  Potential_Savings_Eating_Out     19991 non-null  float64
 22  Potential_Savings_Entertainment  19991 non-null  float64
 23  Potential_Savings_Utilities      19991 non-null  float64
 24  Potential_Savings_Healthcare     19991 non-null  float64
 25  Potential_Savings_Education      19991 non-null  float64
 26  Potential_Savings_Miscellaneous  19991 non-null  float64
dtypes: float64(22), int64(2), object(3)
memory usage: 4.3+ MB

In [17]:
print(df.shape)        # rows, cols
print(df.info())       # data types, nulls
print(df.head())       # first rows
print(df.isnull().sum())  # count of missing values

(19991, 27)
<class 'pandas.core.frame.DataFrame'>
Index: 19991 entries, 0 to 20000
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Income                           19991 non-null  float64
 1   Age                              19991 non-null  int64
 2   Dependents                       19991 non-null  int64
 3   Occupation                       19991 non-null  object
 4   City_Tier                        19991 non-null  object
 5   Rent                             19991 non-null  object
 6   Loan_Repayment                   19991 non-null  float64
 7   Insurance                        19991 non-null  float64
 8   Groceries                        19991 non-null  float64
 9   Transport                        19991 non-null  float64
 10  Eating_Out                       19991 non-null  float64
 11  Entertainment                    19991 non-null  float64
 12  Utilities                        19991 non-null  float64
 13  Healthcare                       19991 non-null  float64
 14  Education                        19991 non-null  float64
 15  Miscellaneous                    19991 non-null  float64
 16  Desired_Savings_Percentage       19991 non-null  float64
 17  Desired_Savings                  19991 non-null  float64
 18  Disposable_Income                19991 non-null  float64
 19  Potential_Savings_Groceries      19991 non-null  float64
 20  Potential_Savings_Transport      19991 non-null  float64
 21  Potential_Savings_Eating_Out     19991 non-null  float64
 22  Potential_Savings_Entertainment  19991 non-null  float64
 23  Potential_Savings_Utilities      19991 non-null  float64
 24  Potential_Savings_Healthcare     19991 non-null  float64
 25  Potential_Savings_Education      19991 non-null  float64
 26  Potential_Savings_Miscellaneous  19991 non-null  float64
dtypes: float64(22), int64(2), object(3)
memory usage: 4.3+ MB
None
         Income  Age  Dependents     Occupation City_Tier         Rent  \
0   44637.24964   49           0  Self_Employed    Tier_1  13391.17489
2   50367.60508   35           1        student    Tier_3  7555.140763
3  101455.60020   21           0  Self_Employed    Tier_3  15218.34004
4   24875.28355   52           4   Professional    Tier_2   4975.05671
6  106119.69280   53           0  Self_Employed    Tier_2  21223.93855

   Loan_Repayment    Insurance     Groceries    Transport  ...  \
0        0.000000  2206.490129   6658.768341  2636.970696  ...
2     4612.103386  2201.800050   6313.222081  3221.396403  ...
3     6809.441427  4889.418087  14690.149360  7106.130005  ...
4     3112.609398   635.907170   3034.329665  1276.155163  ...
6        0.000000  4360.202710  12790.390690  6345.738036  ...

   Desired_Savings  Disposable_Income  Potential_Savings_Groceries  \
0      6200.537192       11265.627710                  1685.696222
2      7050.360422       13891.450620                  1466.073984
3     16694.965140       31617.953610                  1875.932770
4      1874.099434        6265.700532                   788.953124
6     18399.564590       41595.325720                  2799.234658

   Potential_Savings_Transport  Potential_Savings_Eating_Out  \
0                   328.895281                    465.769172
2                   473.549752                    410.857129
3                   762.020789                   1241.017448
4                    68.160766                     61.712505
6                   912.958599                    438.009790

   Potential_Savings_Entertainment  Potential_Savings_Utilities  \
0                       195.151320                   678.292859
2                       459.965257                   488.383423
3                       320.190594                  1389.815033
4                       187.173750                   194.117130
6                       541.702363                   838.299989

   Potential_Savings_Healthcare  Potential_Savings_Education  \
0                     67.682471                     0.000000
2                      7.290892                   106.653597
3                    193.502754                     0.000000
4                     47.294591                    67.388120
6                    111.857588                     0.000000

   Potential_Savings_Miscellaneous
0                        85.735517
2                       138.542422
3                       296.041183
4                        96.557076
6                       409.453143

[5 rows x 27 columns]
Income                             0
Age                                0
Dependents                         0
Occupation                         0
City_Tier                          0
Rent                               0
Loan_Repayment                     0
Insurance                          0
Groceries                          0
Transport                          0
Eating_Out                         0
Entertainment                      0
Utilities                          0
Healthcare                         0
Education                          0
Miscellaneous                      0
Desired_Savings_Percentage         0
Desired_Savings                    0
Disposable_Income                  0
Potential_Savings_Groceries        0
Potential_Savings_Transport        0
Potential_Savings_Eating_Out       0
Potential_Savings_Entertainment    0
Potential_Savings_Utilities        0
Potential_Savings_Healthcare       0
Potential_Savings_Education        0
Potential_Savings_Miscellaneous    0
dtype: int64

In [18]:
cols_to_sum = ['Potential_Savings_Groceries',
 'Potential_Savings_Transport',
 'Potential_Savings_Eating_Out',
 'Potential_Savings_Entertainment',
 'Potential_Savings_Utilities',
 'Potential_Savings_Healthcare',
 'Potential_Savings_Education',
 'Potential_Savings_Miscellaneous'
]

df['Potential_savings'] = df[cols_to_sum].sum(axis=1)

In [19]:
df['Loan_to_Income_Ratio'] = (df['Loan_Repayment'] / df['Income']) * 100

In [20]:
df.head(5)

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous,Potential_savings,Loan_to_Income_Ratio
0,44637.24964,49,0,Self_Employed,Tier_1,13391.17489,0.000000,2206.490129,6658.768341,2636.970696,...,1685.696222,328.895281,465.769172,195.151320,678.292859,67.682471,0.000000,85.735517,3507.222842,0.000000
2,50367.60508,35,1,student,Tier_3,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,1466.073984,473.549752,410.857129,459.965257,488.383423,7.290892,106.653597,138.542422,3551.316457,9.156884
3,101455.60020,21,0,Self_Employed,Tier_3,15218.34004,6809.441427,4889.418087,14690.149360,7106.130005,...,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183,6078.520570,6.711745
4,24875.28355,52,4,Professional,Tier_2,4975.05671,3112.609398,635.907170,3034.329665,1276.155163,...,788.953124,68.160766,61.712505,187.173750,194.117130,47.294591,67.388120,96.557076,1511.357063,12.512860
6,106119.69280,53,0,Self_Employed,Tier_2,21223.93855,0.000000,4360.202710,12790.390690,6345.738036,...,2799.234658,912.958599,438.009790,541.702363,838.299989,111.857588,0.000000,409.453143,6051.516130,0.000000

In [21]:
df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous,Potential_savings,Loan_to_Income_Ratio
0,44637.24964,49,0,Self_Employed,Tier_1,13391.17489,0.000000,2206.490129,6658.768341,2636.970696,...,1685.696222,328.895281,465.769172,195.151320,678.292859,67.682471,0.000000,85.735517,3507.222842,0.000000
2,50367.60508,35,1,student,Tier_3,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,1466.073984,473.549752,410.857129,459.965257,488.383423,7.290892,106.653597,138.542422,3551.316457,9.156884
3,101455.60020,21,0,Self_Employed,Tier_3,15218.34004,6809.441427,4889.418087,14690.149360,7106.130005,...,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183,6078.520570,6.711745
4,24875.28355,52,4,Professional,Tier_2,4975.05671,3112.609398,635.907170,3034.329665,1276.155163,...,788.953124,68.160766,61.712505,187.173750,194.117130,47.294591,67.388120,96.557076,1511.357063,12.512860
6,106119.69280,53,0,Self_Employed,Tier_2,21223.93855,0.000000,4360.202710,12790.390690,6345.738036,...,2799.234658,912.958599,438.009790,541.702363,838.299989,111.857588,0.000000,409.453143,6051.516130,0.000000

In [22]:
# Convert all columns to numeric where possible
df = df.apply(pd.to_numeric, errors="coerce").fillna(0)

# Helper function: agar column exist nahi karta toh 0
def safe_col(df, colname):
    return df[colname] if colname in df.columns else 0

# 🔹 Fire / Property Insurance
df["Fire_Property_Insurance"] = safe_col(df, "Insurance") + safe_col(df, "Housing.Status") + safe_col(df, "Utility Bills")

# 🔹 Health Insurance (40% of Insurance)
df["Health_Insurance"] = safe_col(df, "Insurance") * 0.4  

# 🔹 Life Insurance (60% of Insurance)
df["Life_Insurance"] = safe_col(df, "Insurance") * 0.6  

# 🔹 Transport Related
df["Transport_Expenses"] = safe_col(df, "Transport") + safe_col(df, "Travel Expenses")

# 🔹 Accommodation
df["Accommodation"] = safe_col(df, "Rent") + safe_col(df, "Hotel")

# 🔹 Tax Related
df["Tax_Expenses_Final"] = safe_col(df, "Tax Expenses")

# 🔹 Travel Total
df["Travel_Total"] = safe_col(df, "Travel Expenses")

# 🔹 Family Related
df["Family_Total"] = safe_col(df, "Personal_Expenses") + safe_col(df, "Family expenses")

# 🔹 Pet Care
df["Pet_Care"] = safe_col(df, "Pet-care")

print("✅ Columns created successfully!")

✅ Columns created successfully!

In [23]:
print(df.dtypes)

Income                             float64
Age                                  int64
Dependents                           int64
Occupation                         float64
City_Tier                          float64
Rent                               float64
Loan_Repayment                     float64
Insurance                          float64
Groceries                          float64
Transport                          float64
Eating_Out                         float64
Entertainment                      float64
Utilities                          float64
Healthcare                         float64
Education                          float64
Miscellaneous                      float64
Desired_Savings_Percentage         float64
Desired_Savings                    float64
Disposable_Income                  float64
Potential_Savings_Groceries        float64
Potential_Savings_Transport        float64
Potential_Savings_Eating_Out       float64
Potential_Savings_Entertainment    float64
Potential_Savings_Utilities        float64
Potential_Savings_Healthcare       float64
Potential_Savings_Education        float64
Potential_Savings_Miscellaneous    float64
Potential_savings                  float64
Loan_to_Income_Ratio               float64
Fire_Property_Insurance            float64
Health_Insurance                   float64
Life_Insurance                     float64
Transport_Expenses                 float64
Accommodation                      float64
Tax_Expenses_Final                   int64
Travel_Total                         int64
Family_Total                         int64
Pet_Care                             int64
dtype: object

In [24]:
df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Loan_to_Income_Ratio,Fire_Property_Insurance,Health_Insurance,Life_Insurance,Transport_Expenses,Accommodation,Tax_Expenses_Final,Travel_Total,Family_Total,Pet_Care
0,44637.24964,49,0,0.0,0.0,13391.174890,0.000000,2206.490129,6658.768341,2636.970696,...,0.000000,2206.490129,882.596052,1323.894077,2636.970696,13391.174890,0,0,0,0
2,50367.60508,35,1,0.0,0.0,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,9.156884,2201.800050,880.720020,1321.080030,3221.396403,7555.140763,0,0,0,0
3,101455.60020,21,0,0.0,0.0,15218.340040,6809.441427,4889.418087,14690.149360,7106.130005,...,6.711745,4889.418087,1955.767235,2933.650852,7106.130005,15218.340040,0,0,0,0
4,24875.28355,52,4,0.0,0.0,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,12.512860,635.907170,254.362868,381.544302,1276.155163,4975.056710,0,0,0,0
6,106119.69280,53,0,0.0,0.0,21223.938550,0.000000,4360.202710,12790.390690,6345.738036,...,0.000000,4360.202710,1744.081084,2616.121626,6345.738036,21223.938550,0,0,0,0

In [25]:
# 🔹 Fire / Property Insurance = Insurance + Rent + Utilities
df["Fire_Property_Insurance"] = df["Insurance"] + df["Rent"] + df["Utilities"]

# 🔹 Health Insurance = part of Insurance (assume 40%)
df["Health_Insurance"] = df["Insurance"] * 0.4  

# 🔹 Life Insurance = part of Insurance (assume 60%)
df["Life_Insurance"] = df["Insurance"] * 0.6  

# 🔹 Transport Related = Transport + Travel_Total
df["Transport_Expenses"] = df["Transport"] + df["Travel_Total"]

# 🔹 Accommodation = Rent + (Hotel if exists)
if "Hotel" in df.columns:
    df["Accommodation"] = df["Rent"] + df["Hotel"]
else:
    df["Accommodation"] = df["Rent"]

# 🔹 Family Related = Personal + Family_Total
if "Personal_Expenses" in df.columns:
    df["Family_Total"] = df["Personal_Expenses"] + df["Family_Total"]

# 🔹 Pet Care = Already exists, keep as is
df["Pet_Care_Final"] = df["Pet_Care"]

In [26]:
df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Fire_Property_Insurance,Health_Insurance,Life_Insurance,Transport_Expenses,Accommodation,Tax_Expenses_Final,Travel_Total,Family_Total,Pet_Care,Pet_Care_Final
0,44637.24964,49,0,0.0,0.0,13391.174890,0.000000,2206.490129,6658.768341,2636.970696,...,18509.457250,882.596052,1323.894077,2636.970696,13391.174890,0,0,0,0,0
2,50367.60508,35,1,0.0,0.0,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,13125.397921,880.720020,1321.080030,3221.396403,7555.140763,0,0,0,0,0
3,101455.60020,21,0,0.0,0.0,15218.340040,6809.441427,4889.418087,14690.149360,7106.130005,...,26236.308514,1955.767235,2933.650852,7106.130005,15218.340040,0,0,0,0,0
4,24875.28355,52,4,0.0,0.0,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,6703.652904,254.362868,381.544302,1276.155163,4975.056710,0,0,0,0,0
6,106119.69280,53,0,0.0,0.0,21223.938550,0.000000,4360.202710,12790.390690,6345.738036,...,31786.691198,1744.081084,2616.121626,6345.738036,21223.938550,0,0,0,0,0

In [27]:
# 🔹 Insurance Totals
df["Total_Insurance"] = (
    df["Fire_Property_Insurance"] +
    df["Health_Insurance"] +
    df["Life_Insurance"]
)

# 🔹 Travel Totals = Transport + Travel + Accommodation
df["Total_Travel"] = (
    df["Transport_Expenses"] +
    df["Accommodation"]
)

# 🔹 Family Totals = Family_Total (already) + Pet Care + Miscellaneous
df["Total_Family"] = (
    df["Family_Total"] +
    df["Pet_Care_Final"] +
    df["Miscellaneous"]
)

# 🔹 Grand Total (All grouped)
df["Grand_Total_Expenses"] = (
    df["Total_Insurance"] +
    df["Total_Travel"] +
    df["Total_Family"] +
    df["Groceries"] +
    df["Education"] +
    df["Entertainment"] +
    df["Eating_Out"]
)

# Check first rows
print(df[["Total_Insurance","Total_Travel","Total_Family","Grand_Total_Expenses"]].head())

   Total_Insurance  Total_Travel  Total_Family  Grand_Total_Expenses
0     20715.947379  16028.145586    831.525120          47422.372407
2     15327.197971  10776.537166    628.371220          39442.476039
3     31125.726601  22324.470045   2526.055712          78564.845116
4      7339.560074   6251.211873    515.510300          19938.841683
6     36146.893908  27569.676586   2776.771814          86301.409731

In [28]:
df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Accommodation,Tax_Expenses_Final,Travel_Total,Family_Total,Pet_Care,Pet_Care_Final,Total_Insurance,Total_Travel,Total_Family,Grand_Total_Expenses
0,44637.24964,49,0,0.0,0.0,13391.174890,0.000000,2206.490129,6658.768341,2636.970696,...,13391.174890,0,0,0,0,0,20715.947379,16028.145586,831.525120,47422.372407
2,50367.60508,35,1,0.0,0.0,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,7555.140763,0,0,0,0,0,15327.197971,10776.537166,628.371220,39442.476039
3,101455.60020,21,0,0.0,0.0,15218.340040,6809.441427,4889.418087,14690.149360,7106.130005,...,15218.340040,0,0,0,0,0,31125.726601,22324.470045,2526.055712,78564.845116
4,24875.28355,52,4,0.0,0.0,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,4975.056710,0,0,0,0,0,7339.560074,6251.211873,515.510300,19938.841683
6,106119.69280,53,0,0.0,0.0,21223.938550,0.000000,4360.202710,12790.390690,6345.738036,...,21223.938550,0,0,0,0,0,36146.893908,27569.676586,2776.771814,86301.409731

In [29]:
# ===============================
# 🔹 Create Chatbot-Ready Columns
# ===============================

# 1. Actual Savings
df["Actual_Savings"] = df["Income"] - (
    df["Rent"] + df["Loan_Repayment"] + df["Insurance"] + df["Groceries"] +
    df["Transport"] + df["Eating_Out"] + df["Entertainment"] +
    df["Utilities"] + df["Healthcare"] + df["Education"] +
    df["Miscellaneous"] + df["Travel_Total"] + df["Family_Total"] + df["Pet_Care"]
)

# 2. Expense Buckets
df["Housing_Expenses"] = df["Rent"] + df["Utilities"] + df["Loan_Repayment"]
df["Food_Expenses"] = df["Groceries"] + df["Eating_Out"]
df["Transport_Expenses"] = df["Transport"] + df["Travel_Total"]
df["Lifestyle_Expenses"] = df["Entertainment"] + df["Education"] + df["Miscellaneous"] + df["Family_Total"] + df["Pet_Care"]

# 3. Financial Health Indicators
df["Total_Expenses"] = (
    df["Housing_Expenses"] + df["Food_Expenses"] +
    df["Transport_Expenses"] + df["Lifestyle_Expenses"] + df["Insurance"]
)
df["Savings_Rate"] = (df["Actual_Savings"] / df["Income"]) * 100
df["Debt_to_Income_Ratio"] = (df["Loan_Repayment"] / df["Income"]) * 100
df["Expense_to_Income_Ratio"] = (df["Total_Expenses"] / df["Income"]) * 100

# 4. Flags for Recommendations
df["High_Spending_Flag"] = (df["Expense_to_Income_Ratio"] > 70).astype(int)
df["Low_Savings_Flag"] = (df["Savings_Rate"] < df["Desired_Savings_Percentage"]).astype(int)
df["High_Debt_Flag"] = (df["Debt_to_Income_Ratio"] > 40).astype(int)

# ✅ Preview new columns
df.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Housing_Expenses,Food_Expenses,Lifestyle_Expenses,Total_Expenses,Savings_Rate,Debt_to_Income_Ratio,Expense_to_Income_Ratio,High_Spending_Flag,Low_Savings_Flag,High_Debt_Flag
0,44637.24964,49,0,0.0,0.0,13391.174890,0.000000,2206.490129,6658.768341,2636.970696,...,16302.967121,8310.570067,2367.709375,31824.707388,25.238176,0.000000,71.296300,1,0,0
2,50367.60508,35,1,0.0,0.0,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,15535.701257,7827.036457,5511.704445,34297.638612,27.580129,9.156884,68.094639,0,0,0
3,101455.60020,21,0,0.0,0.0,15218.340040,6809.441427,4889.418087,14690.149360,7106.130005,...,28156.331854,19730.398518,5384.249952,65266.528416,31.164326,6.711745,64.330139,0,0,0
4,24875.28355,52,4,0.0,0.0,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,9180.355132,3727.156890,2620.912846,17440.487201,25.188459,12.512860,70.111712,1,0,0
6,106119.69280,53,0,0.0,0.0,21223.938550,0.000000,4360.202710,12790.390690,6345.738036,...,27426.488488,17181.295794,5403.543443,60717.268471,39.196613,0.000000,57.215835,0,0,0

In [30]:
bad_age = df[(df['Age'] < 18) | (df['Age'] > 100) | (df['Age'].isna())]
print("Rows with questionable age:\n", bad_age[['Age']].head())

Rows with questionable age:
      Age
29   200
51   175
83   976
92     4
123    7

In [31]:
print("Before:", df.shape)
# cleaning step
print("After:", df.shape)

Before: (19991, 54)
After: (19991, 54)